version: '2'

services:
  app:
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '5555:5555'
    volumes:
      - .:/usr/src/app
      # prevents host/container contamination
      - /usr/src/app/node_modules
    env_file: .env
    environment:
      - NODE_ENV=development
    depends_on:
      - redis
    command: npm run dev

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"